License under GPLv3
robototes/RapidReact2022 pull request #13
Opened 2022-01-24 20:56 UTC by obj-obj

Having no license can cause [issues](https://choosealicense.com/no-permission/) (although I doubt we'd run into any of them staying unlicensed, might as well..?).

Doesn't necessarily have to be GPL but I thought it was the best default choice.

2022-01-25 07:02 UTC, jamesdooley4 requested changes
https://en.wikipedia.org/wiki/MIT_License (aka https://opensource.org/licenses/MIT ) is fine, but not GPL.  And I'd prefer to just have the LICENSE at the repo root & not a big license boilerplate at the top of every file (especially since a bunch of the code we re-use is under somebody else's license)

2022-01-25 16:25 UTC, obj-obj commented
The reason I don't like MIT is because it requires every distribution of the software to include the same MIT license, so it just gets everywhere

2022-01-26 16:00 UTC, obj-obj commented
Apparently the Unlicense has some weird legal issues so I will change it to dual MIT/Apache2.0

2022-01-28 03:35 UTC, jamesdooley4 approved these changes

2022-01-29 20:18 UTC, merged