[WIP] Kotlin
robototes/RapidReact2022 pull request #15
Opened 2022-01-25 01:55 UTC by obj-obj

Please actually consider this, I think Kotlin is a much better language than java

There shouldn't be very much overhead for everyone to learn kotlin, considering it's extremely similar to java and that I haven't ever used kotlin before today. In exchange we get non-nullable types among other things.

2022-01-25 02:08 UTC, obj-obj commented
I brought the code to a few people who have never seen kotlin before and they understood it fine, so perhaps no overhead

I've also been on the kotlin docs for a total of like 30 minutes

We can probably save more time than that writing more concise code

2022-01-25 02:09 UTC, obj-obj commented on build.gradle
> -    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
I removed this because the kotlin plugin already automatically imports a relevant version

2022-01-25 02:10 UTC, obj-obj commented on build.gradle
> +        jvmTarget = "11"
Change kotlin and java JVM targets to be the same

2022-01-25 02:21 UTC, obj-obj commented
I will also handle all the porting work

2022-01-25 02:29 UTC, obj-obj commented
Basically, summing up my argument:

- Kotlin has little to no learning curve for ppl coming from java, because I can port java code to kotlin after under 30 mins on the docs, and because I showed it to multiple people in the programming subteam who've never seen kotlin before, and they understood the code fine without even looking at the docs

- Kotlin has non-nullable types, which can and will prevent some runtime errors

- Kotlin is more concise than java, which might have a positive impact on development times

- I can handle the work of porting existing code to Kotlin (I've already done most of the work, anyway)

- Kotlin has full interop with java

2022-01-25 02:49 UTC, obj-obj commented
We have go from mentors if all subteams agree
pog

2022-01-25 03:37 UTC, obj-obj commented
Another mentor says no :(

idk whoever reviews PRs can decide

2022-01-25 19:22 UTC, obj-obj commented
I think this PR is ready, the only files that aren't Kotlin are the template files from WPILIB

2022-01-25 23:19 UTC, obj-obj commented
There are no java files left in the repo now

2022-01-27 16:31 UTC, 1198159 commented
no

2022-01-27 20:14 UTC, obj-obj commented
> no

yes
java bad kotlin good

2022-01-28 03:35 UTC, jamesdooley4 requested changes
Let's chat more as a team about this on Friday.

2022-01-28 23:16 UTC, obj-obj commented
> Let's chat more as a team about this on Friday.

Yeah I was planning to do that, most ppl seemed against it on Monday but I've been maintaining it during the week just in case

2022-01-29 01:31 UTC, obj-obj commented
Team discussion -> whole repo shouldn't be in kotlin (not really surprising, but I might as well try)

2022-01-29 01:31 UTC, closed without merging