Create index subsystem and some commands
robototes/RapidReact2022 pull request #50
Opened 2022-02-05 22:13 UTC by jamietheraccoon

Started index and added basic methods

uses two motors and two color sensors, might change later
Created four commands to work with the subsystem (in and out commands for both motors)
Also updated Hardware.java and Subsystems.java

2022-02-05 22:17 UTC, kirbt commented
> Started index and added basic methods
> 
> uses two motors and two color sensors, might change later Created four commands to work with the subsystem (in and out commands for both motors) Also updated Hardware.java and Subsystems.java

thats awesdome

2022-02-08 01:36 UTC, jamesdooley4 approved these changes

2022-02-08 01:36 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystem/IndexSubsystem.java
Please move this up so it's alphabetically sorted with the other imports.

2022-02-08 01:36 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystem/IndexSubsystem.java
> +        this.feederMotor.configSupplyCurrentLimit(MAX_MOTOR_CURRENT);
Please first reset the motor configs to their default state, then put them in brake mode before configuring the current limit.

2022-02-08 01:36 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystem/IndexSubsystem.java
> +        return (ingestColorSensor.getProximity() > 1500); // value not 1500, to be determined actual value
Please add names for the proximity sensor value so it can be changed in one place & update everywhere it's used.

2022-02-08 01:36 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystem/IndexSubsystem.java
> +    private ColorMatch colorMatcher = new ColorMatch();
This currently isn't used anywhere - is it needed?

2022-02-08 02:51 UTC, bobtseattle reviewed
It would be good to get feedback from Alex S to make sure the logic matches the design.

2022-02-08 02:51 UTC, bobtseattle commented on src/main/java/frc/team2412/robot/subsystem/IndexSubsystem.java
> +        if (ingestSensorHasBallIn()) {
No need to have conditionals.  Should be able to set ingestBallState to ingestSensorHasBallIn();

2022-02-08 02:51 UTC, bobtseattle commented on src/main/java/frc/team2412/robot/subsystem/IndexSubsystem.java
> +        if (feederSensorHasBallIn()) {
No need to have conditionals.  Should be able to set ingestBallState to ingestSensorHasBallIn();

2022-02-08 02:51 UTC, bobtseattle commented on src/main/java/frc/team2412/robot/subsystem/IndexSubsystem.java
> +        if (!ingestSensorHasBallIn()) {
Probably not the right place to put this logic.  Whether or not it stops based on presence may or may depend on the command being executed.  If the drive team wants indexing to stop, it should stop.

2022-02-08 02:51 UTC, bobtseattle commented on src/main/java/frc/team2412/robot/commands/index/IndexIngestMotorOutCommand.java
> +        if (!subsystem.ingestSensorHasBallIn()) {
Is the logic here correct?  Will it ever start if there is a ball in the feeder position and we want it out?

2022-02-08 02:51 UTC, bobtseattle commented on src/main/java/frc/team2412/robot/commands/index/IndexIngestMotorInCommand.java
> +        if (!subsystem.ingestSensorHasBallIn()) {
Will this ever run for more than one tick if the index is empty?

2022-02-08 02:53 UTC, jamesdooley4 approved these changes

2022-02-08 02:53 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystem/IndexSubsystem.java
> +        public static Color RED_CARGO_COLOR = new Color(1, 0, 0);
These aren't used either - can they be deleted, or is code missing that should use them?

2022-02-08 02:53 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystem/IndexSubsystem.java
> +        this.feederMotor.setNeutralMode(NeutralMode.Coast);
Should be brake mode, so the balls stop when the motors stop (coast mode will let the balls be pushed around)

2022-02-10 01:43 UTC, jamesdooley4 approved these changes

2022-02-10 01:43 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/Subsystems.java
> +        public static final boolean INTAKE_ENABLED = true;
These don't actually work since the motor CAN ids are all 0, so I'd recommend leaving them at 'false' for the main code.

2022-02-10 02:28 UTC, jamesdooley4 requested changes

2022-02-10 02:28 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/Hardware.java
> +        public static final int INDEX_1 = 40, INDEX_2 = 41, INDEX_SENSOR_1 = 42, INDEX_SENSOR_2 = 43;
The color sensors aren't on the CAN bus, so their IDs are relative to how the multiplexer works (which uses indexes 0..7)

2022-02-10 02:28 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/Hardware.java
> +        public static final int INDEX_1 = 40, INDEX_2 = 41, INDEX_SENSOR_1 = 42, INDEX_SENSOR_2 = 43;
Consider naming these differently to make it clear which are CAN IDs and which aren't.  Something like `INDEX_MOTOR_1` and `INDEX_COLOR_SENSOR_INGEST`

2022-02-10 02:28 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/Hardware.java
Recommend naming these based on their location (feeder or ingest) instead of just first & second

2022-02-10 02:28 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/Hardware.java
Ditto for the motors, if they are in different places (left / right)?

2022-02-10 02:28 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/commands/index/IndexCommand.java
> +    }
Need to add `addRequirements(subsystem)` so two commands using the index subsystem don't run at the same time.

2022-02-10 02:28 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystem/IndexSubsystem.java
Please move this up into its alphabetical position

2022-02-10 02:28 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystem/IndexSubsystem.java
> +    // }
Delete for now - you can always add it back later if it's needed

2022-02-10 02:48 UTC, bobtseattle reviewed
Added extra work to rename since you are looking for things to do :)

2022-02-10 02:48 UTC, bobtseattle commented on src/main/java/frc/team2412/robot/commands/index/IndexCommand.java
> +    @Override
I would remove since it is empty.

2022-02-10 02:48 UTC, bobtseattle commented on src/main/java/frc/team2412/robot/Hardware.java
> +        public static final int INDEX_1 = 40, INDEX_2 = 41, INDEX_SENSOR_1 = 42, INDEX_SENSOR_2 = 43;
Consider renaming index 1 and 2 constants to match the subsystem so there is no confusion.

2022-02-10 02:48 UTC, bobtseattle commented on src/main/java/frc/team2412/robot/Hardware.java
> +            firstIndexMotor = new WPI_TalonFX(INDEX_1);
Consider renaming index 1 and 2 to match the subsystem so there is no confusion.

2022-02-10 03:36 UTC, jamesdooley4 requested changes

2022-02-10 03:36 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/Subsystems.java
Shouldn't need to be `static`. If something needs it to be static, that's a bug in that code...

2022-02-10 03:36 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/commands/index/IndexShootCommand.java
> +        subsystem.feederMotorStop();
?? This should immediately stop the motors but keep the command running, which seems odd.  The previous code seemed more correct:
```
        // stop motors when there are no balls left
        if (!subsystem.ingestSensorHasBallIn() && !subsystem.feederSensorHasBallIn()) {
            subsystem.ingestMotorStop();
            subsystem.feederMotorStop();
            return true;
        }
```

2022-02-10 03:36 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/commands/index/IndexSpitCommand.java
> +        subsystem.feederMotorStop();
Delete - this is just checking if the command is done and shouldn't be changing the motors

2022-02-10 03:36 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/commands/index/IndexSpitCommand.java
> +        subsystem.feederMotorStop();
If you want to stop the motors when the command ends, add that in a different method:
```
    @Override
    public void end(boolean interrupted) {
        ...
    }
````

2022-02-12 01:29 UTC, merged