Subsystem for Power Logging
robototes/RapidReact2022 pull request #69
Opened 2022-02-10 02:31 UTC by 1toldyou

still working on this
especially not sure I'm imported the correct hardware or not

2022-02-10 03:32 UTC, 1toldyou commented
having some difficulties on initialize the PDP (unable to find the CAN ID)
since the new robot will have different brand of PDP and wiring, so I'll wait till the new robot finished to continue

2022-02-10 03:46 UTC, jamesdooley4 approved these changes

2022-02-10 03:46 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/Hardware.java
> +        public static final int PDP_CAN_ID = 9;
This isn't 0 or 1.  Do we use a non-default CAN ID for the power distribution panel?  If so, add a comment saying that so someone doesn't "fix" this and break it.

2022-02-10 03:46 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/Hardware.java
> +            // powerDistributionPanel = new PowerDistribution();
Delete unused code

2022-02-10 11:39 UTC, TAKBS2412 approved these changes
To find the CAN ID for the CTRE power distribution panel, there is the Phoenix Tuner: [https://docs.ctre-phoenix.com/en/stable/ch03_PrimerPhoenixSoft.html](https://docs.ctre-phoenix.com/en/stable/ch03_PrimerPhoenixSoft.html).

For the Rev Robotics power distribution hub, there is the REV hardware client: [https://docs.revrobotics.com/rev-11-1850/rev-hardware-client/getting-started-with-the-rev-hardware-client](https://docs.revrobotics.com/rev-11-1850/rev-hardware-client/getting-started-with-the-rev-hardware-client).

2022-02-10 11:39 UTC, TAKBS2412 commented on src/main/java/frc/team2412/robot/subsystem/MonitoringSubsystem.java
> +    PowerDistribution powerDistributionPanel;
These three variables should start as `private` - we can change later if needed.

2022-03-02 02:10 UTC, bobtseattle reviewed
Sumedh has discovered there may be a plugin for Shuffleboard that displays this more easily than coding a subsystem:
- https://github.com/wpilibsuite/allwpilib/blob/main/wpilibj/src/main/java/edu/wpi/first/wpilibj/shuffleboard/BuiltInWidgets.java
Would have been nice of them to mention somewhere in the docs.

2022-03-08 02:30 UTC, jamesdooley4 requested changes

2022-03-08 02:30 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/subsystem/MonitoringSubsystem.java
> +            channel14current, channel15current;
Not sure this is necessary anymore, as the driver station logs include the current values for all the PDM channels already.

2022-03-25 01:36 UTC, TAKBS2412 commented
It seems that the data logged here is also logged automatically to the driver station. If that is the case, should we just close this PR?

2022-03-25 03:31 UTC, closed without merging