some commands, hardware done? and a little bit of kotlin
robototes/RapidReact2022 pull request #8
Opened 2022-01-23 21:29 UTC by 1198159

kotlin is very cool im not sure what the laptops will think of it ill make java alternative soontm

2022-01-23 23:11 UTC, jamesdooley4 requested changes

2022-01-23 23:11 UTC, jamesdooley4 commented on src/main/java/frc/team2412/robot/util/SwerveConfiguration.kt
> +    fun falcons(): SwerveModule {
Please rename the file to match the class name, so it's easier for developers to find.

2022-01-23 23:11 UTC, jamesdooley4 commented on vendordeps/SdsSwerveLib.json
> +    }
This is an older version, and https://github.com/SwerveDriveSpecialties/swerve-lib/commits/develop shows a subsequent fix for inverted sensors that's in the 1.0.0 version.  Updating this file to the current one from https://raw.githubusercontent.com/SwerveDriveSpecialties/swerve-lib/master/SdsSwerveLib.json should address this.

2022-01-24 02:00 UTC, 1198159 commented on src/main/java/frc/team2412/robot/Hardware.java
> +    public TalonFX indexMotor;
doesnt work because they are set in if loops

2022-01-24 02:17 UTC, jamesdooley4 approved these changes

2022-01-24 02:18 UTC, merged